### ISSUE TITLE
re-referencing order

### ISSUE THREAD

**Issue by anafrancisco** [DouweHorsthuis/EEG_to_ERP_pipeline_stats_R#20]
if re-referencing to a specific channel, that should be done after ICA

**Comment by DouweHorsthuis** [comment]
Moved the re-referencing to the end of that script.it not happens after excluding components. Re-referencing will still cost 1 channel (the channel you re-reference to) and I don't think, but am not sure, if you can still use the ICA weights. I would not recommend using them without testing it out.
